import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/providers/providers";
import AxiosAuthHeader from "./AxiosAuthHeader";
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="mdl-js" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
           <AxiosAuthHeader />
          {children}
        </Providers>
          <Toaster
          position="bottom-right"
          richColors
          closeButton
          expand
           duration={5000} 
          style={{ zIndex: 999999 }}                 //  đảm bảo luôn trên cùng
          toastOptions={{
            classNames: {
              toast: "text-white",                   //  chữ trắng toàn cục
              title: "text-white",
              description: "text-white/90",
              actionButton: "text-white",
              cancelButton: "text-white",
            },
          }}
        />
      </body>
    </html>
  );
}
